version: '3'

services: 
  db:
    container_name: api_db
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    env_file:
      - .env
    environment: 
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - ./postgres-gymhit-data:/var/lib/postgresql/data
    networks:
      - gymhit-network      

  gymhit:
    build: .
    container_name: gymhit_service
    restart: on-failure
    command: bash -c "yarn && yarn start:$GYMHIT_START_ARG"
    ports:
      - ${GYMHIT_PORT}:${GYMHIT_PORT}
    env_file:
      - .env
    volumes:
      - ./:/usr/src/app
    depends_on:
      - db
    networks:
      - gymhit-network

networks:
  gymhit-network: